# assigns variables to all hosts
# define files with the name of the group (for example: vserv.yaml) to define variables for specific host groups.

all:
  ansible_python_interpreter: /usr/bin/python3
  ansible_user: root
