---
- include_vars: traefik-vault.yaml
- include_vars: traefik-settings.yaml

- name: Clone Traefik Repo
  git:
    repo: 'git@github.com:bjesuiter/vserv-traefik.git'
    dest: '{{traefik_root}}'
    version: 'main'
    update: 'yes'

- name: Create traefik network for web accessability
  docker_network:
    name: web

- name: ensure file availability of acme.json
  file:
    path: '{{traefik_root}}/docker/acme.json'
    state: touch
    # 0600 mode is needed by traefik to be sure, this certificate storage file is not tampered with
    mode: '0600'
    modification_time: preserve
    access_time: preserve

# variable comes from traefik-vault.yaml, as described here:
# https://gist.github.com/tristanfisher/e5a306144a637dc739e7
# password for that encrypted file is configured in root ansible.cfg
- name: Setup doppler cli for this project
  command:
    chdir: '{{traefik_root}}'
    cmd: 'doppler setup --token={{traefik_doppler_token}} --no-prompt'
  register: doppler_result

- name: run traefik via npm
  command:
    cmd: npm start
    chdir: '{{traefik_root}}'
  register: npm_result
# Old way to start traefik (problem: doppler cli will not be started with it)
# - name: Create and start traefik
#   docker_compose:
#     project_src: /home/jb-web-services/services/traefik/
#   register: traefik_compose_output
