---
- name: ensure jb-web-services user
  import_tasks: ensure-services-user.yaml

- name: ensure common filestructure for jb-web-services user
  include: ensure-services-filestructure.yaml
  become: yes
  become_user: jb-web-services

- include: ensure-doppler-cli_debian_ubuntu.yaml

- include: ensure-traefik.yaml
  become: yes
  become_user: jb-web-services
