---
- import_tasks: setup-ansible-target.yaml
- import_tasks: setup-nodejs.yaml
- import_task: setup-duck-cli.yaml
- import_tasks: setup-docker-engine_ubuntu.yaml
  when: ansible_facts['distribution']|lower == 'ubuntu'
- import_tasks: setup-docker-engine_debian.yaml
  when: ansible_facts['distribution']|lower == 'debian'
