---
# Ensure node & npm is available
- name: Remove old repository sources
  apt_repository:
    repo: 'ppa:chris-lea/node.js'
    state: absent

- name: Remove old repository sources
  apt_repository:
    repo: deb https://deb.nodesource.com/node_14.x {{ansible_lsb['codename']}} main
    state: absent

# classic: Confinement policy.
# The classic confinement allows a snap to have the same level of access to the system as “classic” packages,
# like those managed by APT.
- name: Install node snap
  community.general.snap:
    name: node
    classic: yes
    channel: 20/stable
    state: present
